feat: add spam protection via honeypot
eight-labs/formbase pull request #69
Opened 2024-03-19 21:23 UTC by AmoabaKelvin

when a form is filled by a bot, it contains the key `_gotcha` in the formdata, using that, we can identify that the form was submitted by a bot and then flag it as a spam submission.

2024-03-19 23:45 UTC, aikins01 commented
😂😂😂 gotcha, going through

2024-03-20 18:53 UTC, aikins01 reviewed
When does the button appear

2024-03-20 19:16 UTC, AmoabaKelvin commented
> When does the button appear

Button, what do you mean 🤔

2024-03-20 21:31 UTC, aikins01 approved these changes
Looks good 👍

2024-03-20 21:31 UTC, aikins01 commented on src/app/(main)/form/[id]/submissions-table.tsx
> +                      "bg-red-100 duration-300 hover:bg-red-50",
oh, it's the on hover classes that got me here. I was thinking a new button was added

2024-03-22 21:40 UTC, dephraiim requested changes

2024-03-22 21:40 UTC, dephraiim commented on src/app/(main)/form/[id]/submissions-table.tsx
> +                  className={cn(
this isn't how to use `cn`

```js
cn('base class stuff', {
	'class stuff': isLoggedIn,
})

// proper example or something related
className={cn({
  'bg-red-100 duration-300 hover:bg-red-50': row.original.isSpam
})}
```

2024-03-23 01:19 UTC, aikins01 commented on src/app/(main)/form/[id]/submissions-table.tsx
> +                  className={cn(
TIL 😅😅

2024-06-06 23:50 UTC, closed without merging